import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { CheckCircle, Lightbulb, Target, RefreshCw, Download, Loader2 } from 'lucide-react';
import { aiService } from '../services/aiService';
import { generateDemoSummary } from '../data/demoData';

export default function JourneySummary({ nodes, onStartNew, aiEnabled = true }) {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    generateSummary();
  }, []);

  const generateSummary = async () => {
    setLoading(true);
    try {
      let result;

      if (!aiEnabled) {
        // Demo mode - use creative pre-generated summary
        await new Promise(resolve => setTimeout(resolve, 800)); // Simulate thinking
        result = generateDemoSummary(nodes);
      } else {
        // AI mode - generate personalized summary
        result = await aiService.generateJourneySummary(nodes);
      }

      setSummary(result);
    } catch (error) {
      console.error('Failed to generate summary:', error);
      setSummary({
        summary: 'Your decision journey has been completed.',
        keyInsights: ['Multiple perspectives were explored', 'Decisions were made systematically'],
        recommendations: ['Review your journey', 'Take action on insights', 'Continue exploring']
      });
    } finally {
      setLoading(false);
    }
  };

  const downloadJourney = () => {
    const journeyText = nodes.map((node, i) =>
      `Step ${i + 1}: ${node.prompt}\n${node.selectedOption ? `  ↳ Chose: ${node.selectedOption.title}\n` : ''}`
    ).join('\n');

    const fullText = `COGNIFY DECISION JOURNEY
========================

${journeyText}

SUMMARY
=======
${summary?.summary || 'Journey completed'}

KEY INSIGHTS
===========
${summary?.keyInsights?.map((insight, i) => `${i + 1}. ${insight}`).join('\n') || 'N/A'}

RECOMMENDATIONS
==============
${summary?.recommendations?.map((rec, i) => `${i + 1}. ${rec}`).join('\n') || 'N/A'}

Generated by Cognify - AI Decision Pathfinder
`;

    const blob = new Blob([fullText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cognify-journey-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      className="max-w-4xl mx-auto"
    >
      {/* Header */}
      <motion.div
        initial={{ scale: 0 }}
        animate={{ scale: 1 }}
        transition={{ type: "spring", duration: 0.6 }}
        className="text-center mb-8"
      >
        <div className="inline-flex items-center justify-center w-20 h-20 bg-gradient-to-br from-green-400 to-emerald-600 rounded-full mb-4 shadow-xl">
          <CheckCircle className="w-10 h-10 text-white" />
        </div>
        <h1 className="text-4xl font-bold text-gray-900 mb-2">
          Journey Complete! 🎉
        </h1>
        <p className="text-gray-600 text-lg">
          You've explored {nodes.length} step{nodes.length > 1 ? 's' : ''} in your decision journey
        </p>
      </motion.div>

      {/* Summary Card */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="bg-white rounded-2xl shadow-xl p-8 mb-6"
      >
        {loading ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="w-8 h-8 text-indigo-600 animate-spin" />
            <span className="ml-3 text-gray-600">AI is analyzing your journey...</span>
          </div>
        ) : (
          <>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Summary</h2>
            <p className="text-gray-700 text-lg leading-relaxed">
              {summary?.summary}
            </p>
          </>
        )}
      </motion.div>

      {/* Key Insights */}
      {!loading && summary?.keyInsights && summary.keyInsights.length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="bg-gradient-to-r from-purple-50 to-indigo-50 rounded-2xl shadow-lg p-8 mb-6 border-2 border-purple-200"
        >
          <div className="flex items-center gap-3 mb-4">
            <Lightbulb className="w-6 h-6 text-purple-600" />
            <h2 className="text-2xl font-bold text-gray-900">Key Insights</h2>
          </div>
          <ul className="space-y-3">
            {summary.keyInsights.map((insight, index) => (
              <motion.li
                key={index}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.4 + index * 0.1 }}
                className="flex items-start gap-3"
              >
                <span className="flex-shrink-0 w-6 h-6 bg-purple-600 text-white rounded-full flex items-center justify-center text-sm font-bold mt-0.5">
                  {index + 1}
                </span>
                <span className="text-gray-700 flex-1">{insight}</span>
              </motion.li>
            ))}
          </ul>
        </motion.div>
      )}

      {/* Recommendations */}
      {!loading && summary?.recommendations && summary.recommendations.length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
          className="bg-gradient-to-r from-blue-50 to-cyan-50 rounded-2xl shadow-lg p-8 mb-6 border-2 border-blue-200"
        >
          <div className="flex items-center gap-3 mb-4">
            <Target className="w-6 h-6 text-blue-600" />
            <h2 className="text-2xl font-bold text-gray-900">Next Steps</h2>
          </div>
          <ul className="space-y-3">
            {summary.recommendations.map((rec, index) => (
              <motion.li
                key={index}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.6 + index * 0.1 }}
                className="flex items-start gap-3"
              >
                <span className="flex-shrink-0 w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-bold mt-0.5">
                  {index + 1}
                </span>
                <span className="text-gray-700 flex-1">{rec}</span>
              </motion.li>
            ))}
          </ul>
        </motion.div>
      )}

      {/* Actions */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.7 }}
        className="flex flex-wrap gap-4 justify-center"
      >
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={downloadJourney}
          className="flex items-center gap-2 px-6 py-3 bg-gray-700 text-white rounded-xl hover:bg-gray-800 transition-colors shadow-lg"
        >
          <Download className="w-5 h-5" />
          Download Journey
        </motion.button>
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={onStartNew}
          className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-xl hover:from-indigo-700 hover:to-purple-700 transition-colors shadow-lg"
        >
          <RefreshCw className="w-5 h-5" />
          Start New Journey
        </motion.button>
      </motion.div>
    </motion.div>
  );
}
